server:
  port: 9002
spring:
  thymeleaf:
    cache: false

  application:
    name: UserWeb
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:10086/eureka,http://eureka1:10087/eureka
      
    

